// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzlTG09AgFfy2m6v6mfFPRxI9yKcsNnKM',
    appId: '1:458292424505:web:e32ff956b8dfc1775242e8',
    messagingSenderId: '458292424505',
    projectId: 'firstprojectexample',
    authDomain: 'firstprojectexample.firebaseapp.com',
    storageBucket: 'firstprojectexample.firebasestorage.app',
    measurementId: 'G-64JW11YQZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk4aHFfHrPwM3XofiBLq3tNop9hI029RY',
    appId: '1:458292424505:android:d1c28c9fa04620d15242e8',
    messagingSenderId: '458292424505',
    projectId: 'firstprojectexample',
    storageBucket: 'firstprojectexample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLZsfDWBlNnJQriYyA6N1qHjTviUIfbY',
    appId: '1:458292424505:ios:51c29d437977bd0f5242e8',
    messagingSenderId: '458292424505',
    projectId: 'firstprojectexample',
    storageBucket: 'firstprojectexample.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLZsfDWBlNnJQriYyA6N1qHjTviUIfbY',
    appId: '1:458292424505:ios:51c29d437977bd0f5242e8',
    messagingSenderId: '458292424505',
    projectId: 'firstprojectexample',
    storageBucket: 'firstprojectexample.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzlTG09AgFfy2m6v6mfFPRxI9yKcsNnKM',
    appId: '1:458292424505:web:b71fe84c123cb4d75242e8',
    messagingSenderId: '458292424505',
    projectId: 'firstprojectexample',
    authDomain: 'firstprojectexample.firebaseapp.com',
    storageBucket: 'firstprojectexample.firebasestorage.app',
    measurementId: 'G-5L2LWNTDSP',
  );
}
